FROM zhuoqiw/ros-test:latest AS test

FROM ros:galactic

COPY --from=test /opt/Galaxy_camera/lib/*/* /usr/lib/
COPY --from=test /opt/opencv /opt/opencv
COPY --from=test /opt/pcl /opt/pcl
COPY --from=test /ws/install /ws/install

RUN sed 's?opt/ros/$ROS_DISTRO?ws/install?g' ros_entrypoint.sh
