FROM ros:galactic

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  wget \
  # PCL dependencies
  libboost-dev \
  libboost-filesystem-dev \
  libboost-date-time-dev \
  libboost-iostreams-dev \
  libboost-system-dev \
  libflann-dev \
  && rm -rf /var/lib/apt/lists/*

# Build pcl
RUN wget -O pcl.tar.gz https://github.com/PointCloudLibrary/pcl/archive/refs/tags/pcl-1.12.0.tar.gz \
  && tar -xzf pcl.tar.gz \
  && rm pcl.tar.gz
