FROM zhuoqiw/ros-build:latest AS build

FROM ros:galactic

COPY . /ws
COPY --from=build /opt/Galaxy_camera /opt/Galaxy_camera
COPY --from=build /opt/opencv /opt/opencv
COPY --from=build /opt/pcl /opt/pcl
COPY --from=build /ws/install /ws/install

# source entrypoint setup
RUN sed --in-place --expression \
  '$isource "/ws/install/setup.bash"' \
  /ros_entrypoint.sh
