name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build-ros-image:
    name: Build ros image
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v9
        with:
          files: Dockerfile_build
      -
        name: Set up QEMU
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_build
          platforms: linux/amd64
          push: true
          tags: zhuoqiw/ros-build
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-test-src:
    name: Build and test src
    needs: build-ros-image
    runs-on: ubuntu-20.04
    container: 
      image: zhuoqiw/ros
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: /ros_entrypoint.sh colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
      - name: Test
        run: /ros_entrypoint.sh colcon test --event-handlers console_direct+ --packages-skip motor motor_encoder inclinometer
  deployment:
    name: Deployment
    needs: build-test-src
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile_deploy
          platforms: linux/amd64
          push: true
          tags: zhuoqiw/ros-deploy
