name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  opencv:
    name: Build opencv
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v8
        with:
          files: docker/opencv/Dockerfile
      -
        name: Check and set env
        if: steps.changed-files.outputs.any_changed
        run: echo "any_changed=true" >> $GITHUB_ENV
      -
        name: Set up QEMU
        if: env.any_changed
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: env.any_changed
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        if: env.any_changed
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/opencv
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        if: env.any_changed
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        if: env.any_changed
        uses: docker/build-push-action@v2
        with:
          context: ./docker/opencv
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ros-opencv:latest
          cache-from: type=local,src=/tmp/.buildx-cache/opencv
          cache-to: type=local,dest=/tmp/.buildx-cache-new/opencv
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        if: env.any_changed
        run: |
          rm -rf /tmp/.buildx-cache/opencv
          mv /tmp/.buildx-cache-new/opencv /tmp/.buildx-cache/opencv
  pcl:
    name: Build pcl
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v8
        with:
          files: docker/pcl/Dockerfile
      -
        name: Check and set env
        if: steps.changed-files.outputs.any_changed
        run: echo "any_changed=true" >> $GITHUB_ENV
      -
        name: Set up QEMU
        if: env.any_changed
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: env.any_changed
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        if: env.any_changed
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/pcl
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        if: env.any_changed
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        if: env.any_changed
        uses: docker/build-push-action@v2
        with:
          context: ./docker/pcl
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ros-pcl:latest
          cache-from: type=local,src=/tmp/.buildx-cache/pcl
          cache-to: type=local,dest=/tmp/.buildx-cache-new/pcl
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        if: env.any_changed
        run: |
          rm -rf /tmp/.buildx-cache/pcl
          mv /tmp/.buildx-cache-new/pcl /tmp/.buildx-cache/pcl
        
