name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Build ROS docker image
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - 
        name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v8
        with:
          files: docker/Dockerfile
      -
        name: check
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/build-push-action
        with:
          context: ./docker
  job2:
    name: Build ROS docker image 2
    runs-on: ubuntu-20.04
    steps:
      -
        name: Test
        run: echo {{ $GITHUB_ENV }}
        
